# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
  # Development
  - test
  - build
  - deploy-to-dev
  - deploy-to-staging
  - deploy-to-prod

  # Create versions and iterate on relase candidates
  - version
  - iterate
  - create-hotfix
  # Accept a version and push it to the master branch
  - accept


before_script:
  - python -V # Print out python version for debugging
  - conda create -y -p ./environment python=3.7
  - source activate ./environment
  - pip install --upgrade pip
  # Conda needs to install virtualenv for tox to work
  - conda install virtualenv
  - pip install -r requirements_dev.txt

test:
  stage: test
  script:
    - python setup.py test
    - pip install tox pylint
    - tox -e py37,pylint

build:
  stage: build
  script:
    - git describe --tags > version.txt
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl

deploy-to-dev:
  stage: deploy-to-dev
  dependencies:
    - build
  script:
    - sudo /opt/sysman/cmd/deploy/dev/products/seqreports $CI_PROJECT_ID $CI_PIPELINE_ID
  tags:
    - deploys
  only:
    - develop

deploy-to-staging:
  stage: deploy-to-staging
  dependencies:
    - build
  script:
    - sudo /opt/sysman/cmd/deploy/staging/products/seqreports $CI_PROJECT_ID $CI_PIPELINE_ID
  tags:
    - deploys
  only:
    - next

deploy-to-prod:
  stage: deploy-to-prod
  dependencies:
    - build
  script:
    - sudo /opt/sysman/cmd/deploy/prod/products/seqreports $CI_PROJECT_ID $CI_PIPELINE_ID
  tags:
    - deploys
  only:
    - master

pages:
  script:
    - pip install .
    - pip install sphinx sphinx-rtd-theme
    - make docs
  artifacts:
    paths:
      - docs/_build/html/
  only:
    - master

# NOTE: gitlab doesn't (yet) provide parameters to a manual step, so versioning
# is handled by 4 different manual tasks (major, minor, patch, rc) HACK
# https://gitlab.com/gitlab-org/gitlab-ce/issues/24935
# NOTE: The user might accidentally choose more than one of these. When
# they provide variables, this should not be an issue.
major:
  when: manual
  stage: version
  script:
    - change-version major "#arteria-ops"
  only:
    - next
  tags:
    - linux

minor:
  when: manual
  stage: version
  script:
    - change-version minor "#arteria-ops"
  only:
    - next
    - hotfix
  tags:
    - linux

patch:
  when: manual
  stage: version
  script:
    - change-version patch "#arteria-ops"
  only:
    - next
    - hotfix
  tags:
    - linux

iterate:
  when: manual
  stage: iterate
  script:
    - change-version rc "#arteria-ops"
  only:
    - next
    - hotfix
  tags:
    - linux

accept:
  when: manual
  stage: accept
  script:
    - echo "Removing the RC tag from the current version"
    - change-version accept "#arteria-ops"
    - echo "Pushing to the master branch on gitlab"
    - git checkout -B master
    - git remote set-url origin --push git@gitlab.snpseq.medsci.uu.se:shared/snpseq_packs.git
    - ssh-agent bash -c "ssh-add ~/.ssh/gitlab-runner; git push origin master"
  only:
    - next
  tags:
    - linux

sync-branches:
  stage: accept
  script:
    - echo "Pushing to the develop branch on gitlab"
    - git checkout -B develop
    - git remote set-url origin --push git@gitlab.snpseq.medsci.uu.se:shared/snpseq_packs.git
    - ssh-agent bash -c "ssh-add ~/.ssh/gitlab-runner; git push origin develop"
  only:
    - master

create-hotfix:
  stage: create-hotfix
  script:
    - echo "Create a hotfix branch from the current branch (usually master). This will overwrite the current hotfix branch."
    - git checkout -B hotfix
    - git remote set-url origin --push git@gitlab.snpseq.medsci.uu.se:shared/snpseq_packs.git
    - ssh-agent bash -c "ssh-add ~/.ssh/gitlab-runner; git push -f origin hotfix"
  when: manual
  only:
    - develop
  tags:
    - linux
